### ISSUE TITLE
BadZipFile

### ISSUE THREAD

**Issue by FelixNeutatz** [Santosh-Gupta/Research2Vec#1]
Hi,

thanks for your interesting project. Unfortunately, I get the following exception:

```
---------------------------------------------------------------------------
BadZipFile                                Traceback (most recent call last)
<ipython-input-5-487d44a0189f> in <module>()
     65 # UNZIP ZIP
     66 print("Uncompressing zip file")
---> 67 zip_ref = zipfile.ZipFile('model.zip', 'r')
     68 zip_ref.extractall('MODEL/')
     69 zip_ref.close()

~/anaconda/envs/ana41py35/lib/python3.5/zipfile.py in __init__(self, file, mode, compression, allowZip64)
   1024         try:
   1025             if mode == 'r':
-> 1026                 self._RealGetContents()
   1027             elif mode in ('w', 'x'):
   1028                 # set the modified flag so central directory gets written

~/anaconda/envs/ana41py35/lib/python3.5/zipfile.py in _RealGetContents(self)
   1091             raise BadZipFile("File is not a zip file")
   1092         if not endrec:
-> 1093             raise BadZipFile("File is not a zip file")
   1094         if self.debug > 1:
   1095             print(endrec)

BadZipFile: File is not a zip file
```
What do I do wrong?

Best regards,
Felix

**Comment by Santosh-Gupta** [comment]
It looks like the model is not downloading correctly. 

There should be a 'model.zip' file in your local drive. 

Can you run 

`os.path.getsize('model.zip')`

After you get the error to check the size of the file? It should be ~ 2 gbs

Also, are running this directly from Google Colab?

**Comment by FelixNeutatz** [comment]
The content of the file 'model.zip' is as follows:
```
<HTML>
<HEAD>
<TITLE>Not Found</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Not Found</H1>
<H2>Error 404</H2>
</BODY>
</HTML>
```
Seems like the download does not work :(

**Comment by Santosh-Gupta** [comment]
What process did you use to run the notebook? 

For example, did you download the notebook into your environment? Copy and paste the code? Save the notebook to your drive and run it from where? 

Can you confirm that your enviroment is running Python 3?

**Comment by FelixNeutatz** [comment]
I run:
```
felix@Tardis:~/Software$ git clone https://github.com/Santosh-Gupta/Research2Vec.git
felix@Tardis:~/Software/Research2Vec$ source activate ana41py35
%installed all necessary packages ...
(ana41py35) felix@Tardis:~/Software/Research2Vec$ ipython notebook
```
As you see here, I run Python 3:
![selection_156](https://user-images.githubusercontent.com/5217389/45599734-42933280-b9f1-11e8-8bd6-9b955b501e37.png)

**Comment by FelixNeutatz** [comment]
But, if I run it in https://colab.research.google.com it works :)

**Comment by Santosh-Gupta** [comment]
Ok cool! I'm not familiar with running the notebook outside of Colab haha
